#import "./CategoryFragment.gql"

mutation updateOneCategory($data: CategoryUpdateInput! $where: CategoryWhereUniqueInput!) {
    updateOneCategory(data: $data where: $where) {
        ...category
    }
}